version: "3.6"
services:
  app:
    build: ./app
    env_file: app/.env
    tty: true
    volumes: 
    - "./app/wishlist:/app/wishlist"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    build: ./db
    env_file: db/.env
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - /www/static
      - './app/wishlist/static/:/app/static'
    depends_on:
      - app
